//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JagexAccountSwitcher.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JagexAccountSwitcher.Languages.Strings.es", typeof(Strings_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestor de Cuentas.
        /// </summary>
        internal static string AccountHandler {
            get {
                return ResourceManager.GetString("AccountHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Cuenta.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen de Cuentas.
        /// </summary>
        internal static string AccountOverview {
            get {
                return ResourceManager.GetString("AccountOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorar.
        /// </summary>
        internal static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar Lanzador de Jagex.
        /// </summary>
        internal static string CleanJagexLauncher {
            get {
                return ResourceManager.GetString("CleanJagexLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar integración con el lanzador de Jagex.
        /// </summary>
        internal static string CleanJagexLauncherDescription {
            get {
                return ResourceManager.GetString("CleanJagexLauncherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones del Cliente.
        /// </summary>
        internal static string ClientOptions {
            get {
                return ResourceManager.GetString("ClientOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación de Configuraciones.
        /// </summary>
        internal static string ConfigurationsLocation {
            get {
                return ResourceManager.GetString("ConfigurationsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de las configuraciones.
        /// </summary>
        internal static string ConfigurationsPathWatermark {
            get {
                return ResourceManager.GetString("ConfigurationsPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo Depuración.
        /// </summary>
        internal static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar opciones adicionales de depuración.
        /// </summary>
        internal static string DebugModeDescription {
            get {
                return ResourceManager.GetString("DebugModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo Desarrollador.
        /// </summary>
        internal static string DeveloperMode {
            get {
                return ResourceManager.GetString("DeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar herramientas y registro para desarrolladores.
        /// </summary>
        internal static string DeveloperModeDescription {
            get {
                return ResourceManager.GetString("DeveloperModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshabilitar Telemetría.
        /// </summary>
        internal static string DisableTelemetry {
            get {
                return ResourceManager.GetString("DisableTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evitar envío de estadísticas de uso.
        /// </summary>
        internal static string DisableTelemetryDescription {
            get {
                return ResourceManager.GetString("DisableTelemetryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshabilitar Actualización del Walker.
        /// </summary>
        internal static string DisableWalkerUpdate {
            get {
                return ResourceManager.GetString("DisableWalkerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evitar actualizaciones automáticas del componente walker.
        /// </summary>
        internal static string DisableWalkerUpdateDescription {
            get {
                return ResourceManager.GetString("DisableWalkerUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guía.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene Argumentos de Cliente.
        /// </summary>
        internal static string HasClientArguments {
            get {
                return ResourceManager.GetString("HasClientArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        internal static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Cuenta.
        /// </summary>
        internal static string ImportAccount {
            get {
                return ResourceManager.GetString("ImportAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saltar TLS Inseguro.
        /// </summary>
        internal static string InsecureSkipTls {
            get {
                return ResourceManager.GetString("InsecureSkipTls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omitir la validación de certificados TLS (no recomendado).
        /// </summary>
        internal static string InsecureSkipTlsDescription {
            get {
                return ResourceManager.GetString("InsecureSkipTlsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL de JavConfig.
        /// </summary>
        internal static string JavConfigUrl {
            get {
                return ResourceManager.GetString("JavConfigUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce URL para JavConfig.
        /// </summary>
        internal static string JavConfigUrlWatermark {
            get {
                return ResourceManager.GetString("JavConfigUrlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminar.
        /// </summary>
        internal static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar todas las cuentas con un retraso entre cada una.
        /// </summary>
        internal static string MassStartTooltip {
            get {
                return ResourceManager.GetString("MassStartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depuración de Microbot.
        /// </summary>
        internal static string MicrobotDebug {
            get {
                return ResourceManager.GetString("MicrobotDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar características de depuración de Microbot.
        /// </summary>
        internal static string MicrobotDebugDescription {
            get {
                return ResourceManager.GetString("MicrobotDebugDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación del JAR de Microbot.
        /// </summary>
        internal static string MicrobotJarLocation {
            get {
                return ResourceManager.GetString("MicrobotJarLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta del archivo JAR de Microbot.
        /// </summary>
        internal static string MicrobotJarPathWatermark {
            get {
                return ResourceManager.GetString("MicrobotJarPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navegación.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguno.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Actualización.
        /// </summary>
        internal static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omitir comprobación de actualizaciones de RuneLite.
        /// </summary>
        internal static string NoUpdateDescription {
            get {
                return ResourceManager.GetString("NoUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones Con Valores.
        /// </summary>
        internal static string OptionsWithValues {
            get {
                return ResourceManager.GetString("OptionsWithValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de Proceso.
        /// </summary>
        internal static string ProcessID {
            get {
                return ResourceManager.GetString("ProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de Vida del Proceso.
        /// </summary>
        internal static string ProcessLifetime {
            get {
                return ResourceManager.GetString("ProcessLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce nombre del perfil.
        /// </summary>
        internal static string ProfileWatermark {
            get {
                return ResourceManager.GetString("ProfileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host del Proxy.
        /// </summary>
        internal static string ProxyHost {
            get {
                return ResourceManager.GetString("ProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce dirección del host.
        /// </summary>
        internal static string ProxyHostWatermark {
            get {
                return ResourceManager.GetString("ProxyHostWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña del Proxy.
        /// </summary>
        internal static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce contraseña.
        /// </summary>
        internal static string ProxyPasswordWatermark {
            get {
                return ResourceManager.GetString("ProxyPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto del Proxy.
        /// </summary>
        internal static string ProxyPort {
            get {
                return ResourceManager.GetString("ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce número de puerto.
        /// </summary>
        internal static string ProxyPortWatermark {
            get {
                return ResourceManager.GetString("ProxyPortWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Proxy.
        /// </summary>
        internal static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario del Proxy.
        /// </summary>
        internal static string ProxyUsername {
            get {
                return ResourceManager.GetString("ProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce nombre de usuario.
        /// </summary>
        internal static string ProxyUsernameWatermark {
            get {
                return ResourceManager.GetString("ProxyUsernameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumentos Sin Procesar.
        /// </summary>
        internal static string RawArguments {
            get {
                return ResourceManager.GetString("RawArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Cuenta Activa.
        /// </summary>
        internal static string RefreshActiveAccount {
            get {
                return ResourceManager.GetString("RefreshActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación de RuneLite.
        /// </summary>
        internal static string RuneliteLocation {
            get {
                return ResourceManager.GetString("RuneliteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta del ejecutable RuneLite.
        /// </summary>
        internal static string RunelitePathWatermark {
            get {
                return ResourceManager.GetString("RunelitePathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo Seguro.
        /// </summary>
        internal static string SafeMode {
            get {
                return ResourceManager.GetString("SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshabilitar complementos externos.
        /// </summary>
        internal static string SafeModeDescription {
            get {
                return ResourceManager.GetString("SafeModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer Argumentos de Cliente.
        /// </summary>
        internal static string SetClientArguments {
            get {
                return ResourceManager.GetString("SetClientArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor de Argumentos de Cliente.
        /// </summary>
        internal static string SetClientArgumentsBuilder {
            get {
                return ResourceManager.GetString("SetClientArgumentsBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guía de Configuración.
        /// </summary>
        internal static string SetupGuide {
            get {
                return ResourceManager.GetString("SetupGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Consola de Depuración.
        /// </summary>
        internal static string ShowDebugConsole {
            get {
                return ResourceManager.GetString("ShowDebugConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS.
        /// </summary>
        internal static string SOCKS {
            get {
                return ResourceManager.GetString("SOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Todos.
        /// </summary>
        internal static string StartAll {
            get {
                return ResourceManager.GetString("StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigue estos pasos para configurar tu cambiador de cuentas:.
        /// </summary>
        internal static string Step1Description {
            get {
                return ResourceManager.GetString("Step1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establece la ruta de RuneLite en la pestaña de Configuraciones.
        /// </summary>
        internal static string Step1Point1 {
            get {
                return ResourceManager.GetString("Step1Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establece la ruta de Configuraciones donde se guardarán tus perfiles.
        /// </summary>
        internal static string Step1Point2 {
            get {
                return ResourceManager.GetString("Step1Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa tu primera cuenta desde la pestaña de Cuentas.
        /// </summary>
        internal static string Step1Point3 {
            get {
                return ResourceManager.GetString("Step1Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa el botón &quot;Cambiar a Cuenta&quot; para activar una cuenta.
        /// </summary>
        internal static string Step1Point4 {
            get {
                return ResourceManager.GetString("Step1Point4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeros Pasos.
        /// </summary>
        internal static string Step1Title {
            get {
                return ResourceManager.GetString("Step1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una vez que estés familiarizado con lo básico, puedes:.
        /// </summary>
        internal static string Step2Description {
            get {
                return ResourceManager.GetString("Step2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer argumentos de cliente personalizados para cada cuenta.
        /// </summary>
        internal static string Step2Point1 {
            get {
                return ResourceManager.GetString("Step2Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar el Gestor de Cuentas Masivo para iniciar múltiples clientes.
        /// </summary>
        internal static string Step2Point2 {
            get {
                return ResourceManager.GetString("Step2Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Microbot para tareas automatizadas.
        /// </summary>
        internal static string Step2Point3 {
            get {
                return ResourceManager.GetString("Step2Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizar el idioma de la aplicación.
        /// </summary>
        internal static string Step2Point4 {
            get {
                return ResourceManager.GetString("Step2Point4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Características Avanzadas.
        /// </summary>
        internal static string Step2Title {
            get {
                return ResourceManager.GetString("Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar a Cuenta.
        /// </summary>
        internal static string SwitchToAccount {
            get {
                return ResourceManager.GetString("SwitchToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retraso de Actualización (ms):.
        /// </summary>
        internal static string UpdateDelayMs {
            get {
                return ResourceManager.GetString("UpdateDelayMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia: Asegúrate de mantener segura la información de tu cuenta. Esta aplicación solo almacena datos localmente en tu dispositivo..
        /// </summary>
        internal static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido al Cambiador de Cuentas de Jagex.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar de Cuenta Jagex.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
