//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JagexAccountSwitcher.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JagexAccountSwitcher.Languages.Strings.pt", typeof(Strings_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrupamento de Contas.
        /// </summary>
        internal static string AccountGroupingTitle {
            get {
                return ResourceManager.GetString("AccountGroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciador de Contas.
        /// </summary>
        internal static string AccountHandler {
            get {
                return ResourceManager.GetString("AccountHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Conta.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visão Geral das Contas.
        /// </summary>
        internal static string AccountOverview {
            get {
                return ResourceManager.GetString("AccountOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativa.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atribuir Contas.
        /// </summary>
        internal static string AssignAccounts {
            get {
                return ResourceManager.GetString("AssignAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contas Disponíveis.
        /// </summary>
        internal static string AvailableAccounts {
            get {
                return ResourceManager.GetString("AvailableAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurar.
        /// </summary>
        internal static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar Launcher da Jagex.
        /// </summary>
        internal static string CleanJagexLauncher {
            get {
                return ResourceManager.GetString("CleanJagexLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover integração com o launcher da Jagex.
        /// </summary>
        internal static string CleanJagexLauncherDescription {
            get {
                return ResourceManager.GetString("CleanJagexLauncherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções do Cliente.
        /// </summary>
        internal static string ClientOptions {
            get {
                return ResourceManager.GetString("ClientOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização das Configurações.
        /// </summary>
        internal static string ConfigurationsLocation {
            get {
                return ResourceManager.GetString("ConfigurationsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho das configurações.
        /// </summary>
        internal static string ConfigurationsPathWatermark {
            get {
                return ResourceManager.GetString("ConfigurationsPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de Depuração.
        /// </summary>
        internal static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar opções adicionais de depuração.
        /// </summary>
        internal static string DebugModeDescription {
            get {
                return ResourceManager.GetString("DebugModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir arquivos jar antigos.
        /// </summary>
        internal static string DeleteJars {
            get {
                return ResourceManager.GetString("DeleteJars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo Desenvolvedor.
        /// </summary>
        internal static string DeveloperMode {
            get {
                return ResourceManager.GetString("DeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar ferramentas e registro para desenvolvedores.
        /// </summary>
        internal static string DeveloperModeDescription {
            get {
                return ResourceManager.GetString("DeveloperModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar Telemetria.
        /// </summary>
        internal static string DisableTelemetry {
            get {
                return ResourceManager.GetString("DisableTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evitar envio de estatísticas de uso.
        /// </summary>
        internal static string DisableTelemetryDescription {
            get {
                return ResourceManager.GetString("DisableTelemetryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar Atualização do Walker.
        /// </summary>
        internal static string DisableWalkerUpdate {
            get {
                return ResourceManager.GetString("DisableWalkerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evitar atualizações automáticas do componente walker.
        /// </summary>
        internal static string DisableWalkerUpdateDescription {
            get {
                return ResourceManager.GetString("DisableWalkerUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membros do Grupo.
        /// </summary>
        internal static string GroupAccounts {
            get {
                return ResourceManager.GetString("GroupAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cor.
        /// </summary>
        internal static string GroupColor {
            get {
                return ResourceManager.GetString("GroupColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Grupo.
        /// </summary>
        internal static string GroupDetails {
            get {
                return ResourceManager.GetString("GroupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrupamento.
        /// </summary>
        internal static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guia.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem Argumentos de Cliente.
        /// </summary>
        internal static string HasClientArguments {
            get {
                return ResourceManager.GetString("HasClientArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        internal static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Conta.
        /// </summary>
        internal static string ImportAccount {
            get {
                return ResourceManager.GetString("ImportAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorar TLS Inseguro.
        /// </summary>
        internal static string InsecureSkipTls {
            get {
                return ResourceManager.GetString("InsecureSkipTls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorar validação de certificados TLS (não recomendado).
        /// </summary>
        internal static string InsecureSkipTlsDescription {
            get {
                return ResourceManager.GetString("InsecureSkipTlsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL do JavConfig.
        /// </summary>
        internal static string JavConfigUrl {
            get {
                return ResourceManager.GetString("JavConfigUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite URL para JavConfig.
        /// </summary>
        internal static string JavConfigUrlWatermark {
            get {
                return ResourceManager.GetString("JavConfigUrlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encerrar.
        /// </summary>
        internal static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar todas as contas com um atraso entre cada uma.
        /// </summary>
        internal static string MassStartTooltip {
            get {
                return ResourceManager.GetString("MassStartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depuração do Microbot.
        /// </summary>
        internal static string MicrobotDebug {
            get {
                return ResourceManager.GetString("MicrobotDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar recursos de depuração do Microbot.
        /// </summary>
        internal static string MicrobotDebugDescription {
            get {
                return ResourceManager.GetString("MicrobotDebugDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização do JAR do Microbot.
        /// </summary>
        internal static string MicrobotJarLocation {
            get {
                return ResourceManager.GetString("MicrobotJarLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho do arquivo JAR do Microbot.
        /// </summary>
        internal static string MicrobotJarPathWatermark {
            get {
                return ResourceManager.GetString("MicrobotJarPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navegação.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        internal static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem Atualização.
        /// </summary>
        internal static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pular verificação de atualizações do RuneLite.
        /// </summary>
        internal static string NoUpdateDescription {
            get {
                return ResourceManager.GetString("NoUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções Com Valores.
        /// </summary>
        internal static string OptionsWithValues {
            get {
                return ResourceManager.GetString("OptionsWithValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID do Processo.
        /// </summary>
        internal static string ProcessID {
            get {
                return ResourceManager.GetString("ProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo de Vida do Processo.
        /// </summary>
        internal static string ProcessLifetime {
            get {
                return ResourceManager.GetString("ProcessLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o nome do perfil.
        /// </summary>
        internal static string ProfileWatermark {
            get {
                return ResourceManager.GetString("ProfileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host do Proxy.
        /// </summary>
        internal static string ProxyHost {
            get {
                return ResourceManager.GetString("ProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o endereço do host.
        /// </summary>
        internal static string ProxyHostWatermark {
            get {
                return ResourceManager.GetString("ProxyHostWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha do Proxy.
        /// </summary>
        internal static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a senha.
        /// </summary>
        internal static string ProxyPasswordWatermark {
            get {
                return ResourceManager.GetString("ProxyPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porta do Proxy.
        /// </summary>
        internal static string ProxyPort {
            get {
                return ResourceManager.GetString("ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o número da porta.
        /// </summary>
        internal static string ProxyPortWatermark {
            get {
                return ResourceManager.GetString("ProxyPortWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Proxy.
        /// </summary>
        internal static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário do Proxy.
        /// </summary>
        internal static string ProxyUsername {
            get {
                return ResourceManager.GetString("ProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o nome de usuário.
        /// </summary>
        internal static string ProxyUsernameWatermark {
            get {
                return ResourceManager.GetString("ProxyUsernameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumentos Brutos.
        /// </summary>
        internal static string RawArguments {
            get {
                return ResourceManager.GetString("RawArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar Conta Ativa.
        /// </summary>
        internal static string RefreshActiveAccount {
            get {
                return ResourceManager.GetString("RefreshActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização do RuneLite.
        /// </summary>
        internal static string RuneliteLocation {
            get {
                return ResourceManager.GetString("RuneliteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho do executável RuneLite.
        /// </summary>
        internal static string RunelitePathWatermark {
            get {
                return ResourceManager.GetString("RunelitePathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo Seguro.
        /// </summary>
        internal static string SafeMode {
            get {
                return ResourceManager.GetString("SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar plugins externos.
        /// </summary>
        internal static string SafeModeDescription {
            get {
                return ResourceManager.GetString("SafeModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string SaveGroup {
            get {
                return ResourceManager.GetString("SaveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Argumentos de Cliente.
        /// </summary>
        internal static string SetClientArguments {
            get {
                return ResourceManager.GetString("SetClientArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construtor de Argumentos de Cliente.
        /// </summary>
        internal static string SetClientArgumentsBuilder {
            get {
                return ResourceManager.GetString("SetClientArgumentsBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guia de Configuração.
        /// </summary>
        internal static string SetupGuide {
            get {
                return ResourceManager.GetString("SetupGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Console de Depuração.
        /// </summary>
        internal static string ShowDebugConsole {
            get {
                return ResourceManager.GetString("ShowDebugConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS.
        /// </summary>
        internal static string SOCKS {
            get {
                return ResourceManager.GetString("SOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Todos.
        /// </summary>
        internal static string StartAll {
            get {
                return ResourceManager.GetString("StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Grupo.
        /// </summary>
        internal static string StartGroup {
            get {
                return ResourceManager.GetString("StartGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siga estes passos para configurar seu alternador de contas:.
        /// </summary>
        internal static string Step1Description {
            get {
                return ResourceManager.GetString("Step1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defina o caminho do RuneLite na aba Configurações.
        /// </summary>
        internal static string Step1Point1 {
            get {
                return ResourceManager.GetString("Step1Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defina o caminho de Configurações onde seus perfis serão armazenados.
        /// </summary>
        internal static string Step1Point2 {
            get {
                return ResourceManager.GetString("Step1Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe sua primeira conta na aba Contas.
        /// </summary>
        internal static string Step1Point3 {
            get {
                return ResourceManager.GetString("Step1Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use o botão &quot;Mudar para Conta&quot; para ativar uma conta.
        /// </summary>
        internal static string Step1Point4 {
            get {
                return ResourceManager.GetString("Step1Point4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiros Passos.
        /// </summary>
        internal static string Step1Title {
            get {
                return ResourceManager.GetString("Step1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depois de se familiarizar com o básico, você pode:.
        /// </summary>
        internal static string Step2Description {
            get {
                return ResourceManager.GetString("Step2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir argumentos de cliente personalizados para cada conta.
        /// </summary>
        internal static string Step2Point1 {
            get {
                return ResourceManager.GetString("Step2Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar o Gerenciador de Contas em Massa para iniciar vários clientes.
        /// </summary>
        internal static string Step2Point2 {
            get {
                return ResourceManager.GetString("Step2Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar o Microbot para tarefas automatizadas.
        /// </summary>
        internal static string Step2Point3 {
            get {
                return ResourceManager.GetString("Step2Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizar o idioma da aplicação.
        /// </summary>
        internal static string Step2Point4 {
            get {
                return ResourceManager.GetString("Step2Point4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos Avançados.
        /// </summary>
        internal static string Step2Title {
            get {
                return ResourceManager.GetString("Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar Grupo.
        /// </summary>
        internal static string StopGroup {
            get {
                return ResourceManager.GetString("StopGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudar para Conta.
        /// </summary>
        internal static string SwitchToAccount {
            get {
                return ResourceManager.GetString("SwitchToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atraso de Atualização (ms):.
        /// </summary>
        internal static string UpdateDelayMs {
            get {
                return ResourceManager.GetString("UpdateDelayMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso: Certifique-se de manter as informações da sua conta seguras. Esta aplicação armazena dados apenas localmente no seu dispositivo..
        /// </summary>
        internal static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo ao Alternador de Contas Jagex.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternador de Contas Jagex.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
