//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JagexAccountSwitcher.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JagexAccountSwitcher.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Grouping.
        /// </summary>
        internal static string AccountGroupingTitle {
            get {
                return ResourceManager.GetString("AccountGroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Handler.
        /// </summary>
        internal static string AccountHandler {
            get {
                return ResourceManager.GetString("AccountHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Overview.
        /// </summary>
        internal static string AccountOverview {
            get {
                return ResourceManager.GetString("AccountOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Accounts.
        /// </summary>
        internal static string AssignAccounts {
            get {
                return ResourceManager.GetString("AssignAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Accounts.
        /// </summary>
        internal static string AvailableAccounts {
            get {
                return ResourceManager.GetString("AvailableAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Jagex Launcher.
        /// </summary>
        internal static string CleanJagexLauncher {
            get {
                return ResourceManager.GetString("CleanJagexLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Jagex launcher integration.
        /// </summary>
        internal static string CleanJagexLauncherDescription {
            get {
                return ResourceManager.GetString("CleanJagexLauncherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Options.
        /// </summary>
        internal static string ClientOptions {
            get {
                return ResourceManager.GetString("ClientOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations Location.
        /// </summary>
        internal static string ConfigurationsLocation {
            get {
                return ResourceManager.GetString("ConfigurationsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to store configurations.
        /// </summary>
        internal static string ConfigurationsPathWatermark {
            get {
                return ResourceManager.GetString("ConfigurationsPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Mode.
        /// </summary>
        internal static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable additional debugging options.
        /// </summary>
        internal static string DebugModeDescription {
            get {
                return ResourceManager.GetString("DebugModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete old jar-files.
        /// </summary>
        internal static string DeleteJars {
            get {
                return ResourceManager.GetString("DeleteJars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Mode.
        /// </summary>
        internal static string DeveloperMode {
            get {
                return ResourceManager.GetString("DeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable developer tools and logging.
        /// </summary>
        internal static string DeveloperModeDescription {
            get {
                return ResourceManager.GetString("DeveloperModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Telemetry.
        /// </summary>
        internal static string DisableTelemetry {
            get {
                return ResourceManager.GetString("DisableTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent sending usage statistics.
        /// </summary>
        internal static string DisableTelemetryDescription {
            get {
                return ResourceManager.GetString("DisableTelemetryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Walker Update.
        /// </summary>
        internal static string DisableWalkerUpdate {
            get {
                return ResourceManager.GetString("DisableWalkerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent automatic updates to the walker component.
        /// </summary>
        internal static string DisableWalkerUpdateDescription {
            get {
                return ResourceManager.GetString("DisableWalkerUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Jagex from receiving process info about JagexAccountSwitcher (Requires to run the switcher as admin).
        /// </summary>
        internal static string EnableProcessBlocking {
            get {
                return ResourceManager.GetString("EnableProcessBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Members.
        /// </summary>
        internal static string GroupAccounts {
            get {
                return ResourceManager.GetString("GroupAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string GroupColor {
            get {
                return ResourceManager.GetString("GroupColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Details.
        /// </summary>
        internal static string GroupDetails {
            get {
                return ResourceManager.GetString("GroupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        internal static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Client Arguments.
        /// </summary>
        internal static string HasClientArguments {
            get {
                return ResourceManager.GetString("HasClientArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        internal static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Account.
        /// </summary>
        internal static string ImportAccount {
            get {
                return ResourceManager.GetString("ImportAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insecure Skip TLS.
        /// </summary>
        internal static string InsecureSkipTls {
            get {
                return ResourceManager.GetString("InsecureSkipTls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip TLS certificate validation (not recommended).
        /// </summary>
        internal static string InsecureSkipTlsDescription {
            get {
                return ResourceManager.GetString("InsecureSkipTlsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavConfig URL.
        /// </summary>
        internal static string JavConfigUrl {
            get {
                return ResourceManager.GetString("JavConfigUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL for JavConfig.
        /// </summary>
        internal static string JavConfigUrlWatermark {
            get {
                return ResourceManager.GetString("JavConfigUrlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start all accounts with a delay between each one.
        /// </summary>
        internal static string MassStartTooltip {
            get {
                return ResourceManager.GetString("MassStartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microbot Debug.
        /// </summary>
        internal static string MicrobotDebug {
            get {
                return ResourceManager.GetString("MicrobotDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Microbot debugging features.
        /// </summary>
        internal static string MicrobotDebugDescription {
            get {
                return ResourceManager.GetString("MicrobotDebugDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microbot Jar Location.
        /// </summary>
        internal static string MicrobotJarLocation {
            get {
                return ResourceManager.GetString("MicrobotJarLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the Microbot Jar file.
        /// </summary>
        internal static string MicrobotJarPathWatermark {
            get {
                return ResourceManager.GetString("MicrobotJarPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update.
        /// </summary>
        internal static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip checking for RuneLite updates.
        /// </summary>
        internal static string NoUpdateDescription {
            get {
                return ResourceManager.GetString("NoUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options With Values.
        /// </summary>
        internal static string OptionsWithValues {
            get {
                return ResourceManager.GetString("OptionsWithValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        internal static string ProcessID {
            get {
                return ResourceManager.GetString("ProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Lifetime.
        /// </summary>
        internal static string ProcessLifetime {
            get {
                return ResourceManager.GetString("ProcessLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter profile name.
        /// </summary>
        internal static string ProfileWatermark {
            get {
                return ResourceManager.GetString("ProfileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Host.
        /// </summary>
        internal static string ProxyHost {
            get {
                return ResourceManager.GetString("ProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter host address.
        /// </summary>
        internal static string ProxyHostWatermark {
            get {
                return ResourceManager.GetString("ProxyHostWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Password.
        /// </summary>
        internal static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string ProxyPasswordWatermark {
            get {
                return ResourceManager.GetString("ProxyPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Port.
        /// </summary>
        internal static string ProxyPort {
            get {
                return ResourceManager.GetString("ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter port number.
        /// </summary>
        internal static string ProxyPortWatermark {
            get {
                return ResourceManager.GetString("ProxyPortWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Type.
        /// </summary>
        internal static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Username.
        /// </summary>
        internal static string ProxyUsername {
            get {
                return ResourceManager.GetString("ProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username.
        /// </summary>
        internal static string ProxyUsernameWatermark {
            get {
                return ResourceManager.GetString("ProxyUsernameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Arguments.
        /// </summary>
        internal static string RawArguments {
            get {
                return ResourceManager.GetString("RawArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Active Account.
        /// </summary>
        internal static string RefreshActiveAccount {
            get {
                return ResourceManager.GetString("RefreshActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runelite Location.
        /// </summary>
        internal static string RuneliteLocation {
            get {
                return ResourceManager.GetString("RuneliteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to RuneLite executable.
        /// </summary>
        internal static string RunelitePathWatermark {
            get {
                return ResourceManager.GetString("RunelitePathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Mode.
        /// </summary>
        internal static string SafeMode {
            get {
                return ResourceManager.GetString("SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable external plugins.
        /// </summary>
        internal static string SafeModeDescription {
            get {
                return ResourceManager.GetString("SafeModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveGroup {
            get {
                return ResourceManager.GetString("SaveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Client Arguments.
        /// </summary>
        internal static string SetClientArguments {
            get {
                return ResourceManager.GetString("SetClientArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Arguments Builder.
        /// </summary>
        internal static string SetClientArgumentsBuilder {
            get {
                return ResourceManager.GetString("SetClientArgumentsBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Guide.
        /// </summary>
        internal static string SetupGuide {
            get {
                return ResourceManager.GetString("SetupGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Debug Console.
        /// </summary>
        internal static string ShowDebugConsole {
            get {
                return ResourceManager.GetString("ShowDebugConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS.
        /// </summary>
        internal static string SOCKS {
            get {
                return ResourceManager.GetString("SOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start All.
        /// </summary>
        internal static string StartAll {
            get {
                return ResourceManager.GetString("StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Group.
        /// </summary>
        internal static string StartGroup {
            get {
                return ResourceManager.GetString("StartGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow these steps to set up your account switcher:.
        /// </summary>
        internal static string Step1Description {
            get {
                return ResourceManager.GetString("Step1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the RuneLite path in the Settings tab.
        /// </summary>
        internal static string Step1Point1 {
            get {
                return ResourceManager.GetString("Step1Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the Configurations path where your profiles will be stored.
        /// </summary>
        internal static string Step1Point2 {
            get {
                return ResourceManager.GetString("Step1Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import your first account from the Accounts tab.
        /// </summary>
        internal static string Step1Point3 {
            get {
                return ResourceManager.GetString("Step1Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the &quot;Switch to Account&quot; button to activate an account.
        /// </summary>
        internal static string Step1Point4 {
            get {
                return ResourceManager.GetString("Step1Point4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        internal static string Step1Title {
            get {
                return ResourceManager.GetString("Step1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you&apos;re familiar with the basics, you can:.
        /// </summary>
        internal static string Step2Description {
            get {
                return ResourceManager.GetString("Step2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set custom client arguments for each account.
        /// </summary>
        internal static string Step2Point1 {
            get {
                return ResourceManager.GetString("Step2Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Mass Account Handler to launch multiple clients.
        /// </summary>
        internal static string Step2Point2 {
            get {
                return ResourceManager.GetString("Step2Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Microbot for automated tasks.
        /// </summary>
        internal static string Step2Point3 {
            get {
                return ResourceManager.GetString("Step2Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the application language.
        /// </summary>
        internal static string Step2Point4 {
            get {
                return ResourceManager.GetString("Step2Point4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Features.
        /// </summary>
        internal static string Step2Title {
            get {
                return ResourceManager.GetString("Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Group.
        /// </summary>
        internal static string StopGroup {
            get {
                return ResourceManager.GetString("StopGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Account.
        /// </summary>
        internal static string SwitchToAccount {
            get {
                return ResourceManager.GetString("SwitchToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Delay (ms):.
        /// </summary>
        internal static string UpdateDelayMs {
            get {
                return ResourceManager.GetString("UpdateDelayMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Make sure to keep your account information secure. This application only stores data locally on your device..
        /// </summary>
        internal static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Jagex Account Switcher.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jagex Account Switcher.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
